#!/bin/sh

while read file
do
  case "$1" in
    "w") setbg "$file" & ;;
    "y") echo -n "$file" | xclip -selection clipboard & ;;
    "r") convert -rotate 90 "$file" "$file" ;;
    "R") convert -rotate -90 "$file" "$file" ;;
    "d") [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted" ;;
    "g") gimp "$file" & ;;
  esac
done
